#
baseURL = "https://rondenmarr.com/"
disablePathToLower = false
languageCode = "en-us"
title = "Ronden Marr"
theme = "hugo-octopress"

disqusShortname = "rondenmarr"
# Number of blog posts in each pagination page
paginate = 6

# Code highlighting options

# Highlight shortcode and code fences (```) will be treated similarly
pygmentscodefences = true

# Use CSS for highlighting
pygmentsuseclasses = true

# pygments options can be added here (and in the highlight shortcode in the markdown file)
# Hugo supports these pygments options: style, encoding, noclasses, hl_lines, linenos
# for example: pygmentsoptions = "linenos=true"

[permalinks]
post = "/post/:year-:month-:day-:title/"

[[menu.main]]
  Name = "Home"
  URL = "/"
  weight = -20

[[menu.main]]
  Name = "News"
  URL = "/post"
  weight = -15

[[menu.main]]
  Name = "Products"
  URL = "/product"
  weight = -10

[[menu.main]]
  Name = "About"
  URL = "/about"
  weight = -5

[[menu.sidebar]]
  Name = "Core Books"
  URL = "/categories/core-book/"
  weight = 1

[[menu.sidebar]]
  Name = "5e Supplements"
  URL = "/categories/5e/"
  weight = 2



[indexes]
   tag = "tags"
   category = "categories"


[params]

  # --- Start sidebar options ---
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit = 5
  sidebarMenuEnabled = true
  sidebarMenuHeader = "Products"
  logo = "Ronden_Marr_Title_Logo.png"
  sidebarText = """

[<img src="/Ronden_Marr_Title_Logo.png" class="sidebarlogo" />](http://drivethrurpg.com/browse/pub/6296/Morgajel/subcategory/19955_23676/Ronden-Marr)
<br/>
Support us on [![dtrpg](/DrivethruRPG.png)](http://drivethrurpg.com/browse/pub/6296/Morgajel/subcategory/19955_23676/Ronden-Marr)
    </br>
    or follow us here:
"""
  twitter = "https://twitter.com/RondenMarr"
  googleplus = "https://plus.google.com/107906699862814290914"
  facebook = "https://www.facebook.com/RondenMarr/"

  navigationNewWindow = false
  truncate = true

  author = "Jesse Morgan"

  # This text appears in site header under website title
  subtitle = "Dwarves may rule with an iron fist, but much worse awaits in The Undercavern."

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so it was added to index.html manually
  continueReadingText = "Delve deeper..."

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  googleAnalytics = "UA-121983314-2"


  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  defaultDescription = "An underground campaign setting for tabletop RPGs"

  notFoundHeader = "This appears to be a dead end."

  notFoundText = "Please either go back or use the navigation/sidebar menus."

  # Set to true to hide ReadingTime on posts
  disableReadingTime = true

  generateTaxonomyList = true

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Remove or Set to false to use local fonts
  remoteFonts = false

  # Remove or set to false to use FontAwesome CDN, otherwise the theme uses ForkAwesome local fonts.
  # fontAwesome = false
  customCSS = ["css/custom.css"]

